version: "3.9"

services:
  web:
    build: .
    container_name: aspnet_mvc_app
    depends_on:
      - db
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    expose:
      - "8080"

  nginx:
    image: nginx:latest
    container_name: nginx_proxy
    ports:
      - "5003:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - web

  db:
    image: postgres:15
    container_name: postgres_db
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypass
      POSTGRES_DB: mydb
    volumes:
      - pgdata:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - db

volumes:
  pgdata:
